/*
 * delays.h
 *
 *  Created on: Jul 1, 2026
 *      Author: hans
 */

#ifndef INC_DELAYS_H_
#define INC_DELAYS_H_

#define DELAY_4 asm("NOP"); asm("NOP"); asm("NOP"); asm("NOP");
#define DELAY_1US DELAY_4 DELAY_4 DELAY_4 DELAY_4;
#define DELAY_10US DELAY_1US DELAY_1US DELAY_1US DELAY_1US DELAY_1US DELAY_1US DELAY_1US DELAY_1US DELAY_1US DELAY_1US

#define DELAY_TWR1L DELAY_4 DELAY_4 DELAY_4 DELAY_4//1
#define DELAY_TWR0L DELAY_1US DELAY_1US DELAY_1US DELAY_1US DELAY_1US DELAY_1US DELAY_1US DELAY_1US DELAY_1US//9
#define DELAY_TRL DELAY_4 DELAY_4 DELAY_4 DELAY_4 DELAY_4 DELAY_4 DELAY_4 DELAY_4 DELAY_4 DELAY_4
#define DELAY_TRSTL DELAY_10US DELAY_10US DELAY_10US DELAY_10US DELAY_10US //50


#endif /* INC_DELAYS_H_ */
